### ISSUE TITLE
 Capacitor android demo app crash in splash screen.

### ISSUE THREAD

**Issue by rengarajan098015** [ionicthemes/ionic6-starter-app#32]
Issue with **ionic5-full-starter-app-pro-version-4.0.0**
**Apk file not works properly** , let me know any changes missing in the document.

 --------- beginning of crash
2021-12-24 18:15:41.659 11964-11964/com.ionicthemes.ionic5fullapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ionicthemes.ionic5fullapp, PID: 11964
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.ionicthemes.ionic5fullapp. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@19.3.0:184)
        at com.google.firebase.auth.FirebaseAuth.getInstance(com.google.firebase:firebase-auth@@19.3.1:1)
        at com.baumblatt.capacitor.firebase.auth.CapacitorFirebaseAuth.load(CapacitorFirebaseAuth.java:72)
        at com.getcapacitor.PluginHandle.load(PluginHandle.java:95)
        at com.getcapacitor.PluginHandle.<init>(PluginHandle.java:59)
        at com.getcapacitor.Bridge.registerPlugin(Bridge.java:503)
        at com.getcapacitor.Bridge.registerAllPlugins(Bridge.java:458)
        at com.getcapacitor.Bridge.<init>(Bridge.java:188)
        at com.getcapacitor.Bridge.<init>(Bridge.java:65)
        at com.getcapacitor.Bridge$Builder.create(Bridge.java:1288)
        at com.getcapacitor.BridgeActivity.load(BridgeActivity.java:72)
        at com.getcapacitor.BridgeActivity.onStart(BridgeActivity.java:110)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-12-24 18:16:41.010 11964-12038/com.ionicthemes.ionic5fullapp E/cr_PlatformSer-Internal: UsageReporting query failed

![Issue](https://user-images.githubusercontent.com/77962234/147354541-848f53f7-1041-47a4-962c-276fc660a19e.jpeg)

**Comment by djabif** [comment]
Which steps did you follow to build the project?

**Comment by rengarajan098015** [comment]
https://ionic-5-full-starter-app-docs.ionicthemes.com/capacitor

https://ionic-5-full-starter-app-docs.ionicthemes.com/capacitor

**Comment by djabif** [comment]
Please follow the [Firebase setup instructions](https://ionic-5-full-starter-app-docs.ionicthemes.com/firebase-integration) from the documentation and let me know if you need further assistance.
